insert into teste.planoconta
(codigo_reduzido, descricao, conta_contabil,
 conta_entidade, conta_estoque, conta_elemento, conta_transferencia, grupo, nivel, conta_final)
values

(1,'A T I V O','1.0.0.00.00.00000','N','N','1','N','1.0.0.00.00.00000',1,'1.9.9.99.99.99999'),
(2,'CIRCULANTE','1.1.0.00.00.00000','N','N','N','N','1.1.0.00.00.00000',2,'1.1.9.99.99.99999'),
(4,'DISPONIVEL','1.1.1.00.00.00000','N','N','N','N','1.1.1.00.00.00000',3,'1.1.1.99.99.99999'),
(5,'DISPONIVEL','1.1.1.01.00.00000','N','N','N','N','1.1.1.01.00.00000',4,'1.1.1.01.99.99999'),
(6,'BENS NUMERARIOS','1.1.1.01.01.00000','N','N','N','N','1.1.1.01.01.00000',5,'1.1.1.01.01.99999'),
(7,'CAIXA','1.1.1.01.01.00100','N','N','N','N','1.1.1.01.01.00000',6,'1.1.1.01.01.00100'),
(8,'BANCOS C/ MOVIMENTO','1.1.1.01.02.00000','N','N','N','N','1.1.1.01.02.00000',5,'1.1.1.01.02.99999'),
(9,'BRADESCO SA','1.1.1.01.02.00300','N','N','N','N','1.1.1.01.02.00000',6,'1.1.1.01.02.00300'),
(10,'BANCO DO BRASIL SA','1.1.1.01.02.00302','N','N','N','N','1.1.1.01.02.00000',6,'1.1.1.01.02.00302'),
(11,'BANCO ABC BRASIL','1.1.1.01.02.00305','N','N','N','N','1.1.1.01.02.00000',6,'1.1.1.01.02.00305'),
(13,'BANCO DAYCOVAL SA','1.1.1.01.02.00307','N','N','N','N','1.1.1.01.02.00000',6,'1.1.1.01.02.00307'),
(15,'BANCO ITAU SA','1.1.1.01.02.00310','N','N','N','N','1.1.1.01.02.00000',6,'1.1.1.01.02.00310');

insert into teste.genero
(id, descricao)
values
(00, 'Serviço.'),
(01, 'Animais vivos.'),
(02, 'Carnes e miudezas, comestíveis.'),
(03, 'Peixes e crustáceos, moluscos e os outros invertebrados aquáticos.'),
(04, 'Leite e laticínios; ovos de aves; mel natural; produtos comestíveis de origem animal, não especificados nem compreendidos em outros Capítulos da TIPI.'),
(05, 'Outros produtos de origem animal, não especificados nem compreendidos em outros Capítulos da TIPI.'),
(06, 'Plantas vivas e produtos de floricultura.'),
(07, 'Produtos hortícolas, plantas, raízes e tubérculos, comestíveis.'),
(08, 'Frutas; cascas de cítricos e de melões.'),
(09, 'Café, chá, mate e especiarias.'),
(10, 'Cereais.'),
(11, 'Produtos da indústria de moagem; malte; amidos e féculas; inulina; glúten de trigo.'),
(12, 'Sementes e frutos oleaginosos; grãos, sementes e frutos diversos; plantas industriais ou medicinais; palha e forragem.'),
(13, 'Gomas, resinas e outros sucos e extratos vegetais.'),
(14, 'Matérias para entrançar e outros produtos de origem vegetal, não especificadas nem compreendidas em outros Capítulos da NCM.'),
(15, 'Gorduras e óleos animais ou vegetais; produtos da sua dissociação; gorduras alimentares elaboradas; ceras de origem animal ou vegetal.'),
(16, 'Preparações de carne, de peixes ou de crustáceos, de moluscos ou de outros invertebrados aquáticos.'),
(17, 'Açúcares e produtos de confeitaria.'),
(18, 'Cacau e suas preparações.'),
(19, 'Preparações à base de cereais, farinhas, amidos, féculas ou de leite; produtos de pastelaria.'),
(20, 'Preparações de produtos hortícolas, de frutas ou de outras partes de plantas.'),
(21, 'Preparações alimentícias diversas.'),
(22, 'Bebidas, líquidos alcoólicos e vinagres.'),
(23, 'Resíduos e desperdícios das indústrias alimentares; alimentos preparados para animais.'),
(24, 'Fumo (tabaco) e seus sucedâneos, manufaturados.'),
(25, 'Sal; enxofre; terras e pedras; gesso, cal e cimento.'),
(26, 'Minérios, escórias e cinzas.'),
(27, 'Combustíveis minerais, óleos minerais e produtos de sua destilação; matérias betuminosas; ceras minerais.'),
(28, 'Produtos químicos inorgânicos; compostos inorgânicos ou orgânicos de metais preciosos, de elementos radioativos, de metais das terras raras ou de isótopos.'),
(29, 'Produtos químicos orgânicos.'),
(30, 'Produtos farmacêuticos.'),
(31, 'Adubos ou fertilizantes.'),
(32, 'Extratos tanantes e tintoriais; taninos e seus derivados; pigmentos e outras matérias corantes, tintas e vernizes, mástiques; tintas de escrever.'),
(33, 'Óleos essenciais e resinóides; produtos de perfumaria ou de toucador preparados e preparações cosméticas.'),
(34, 'Sabões, agentes orgânicos de superfície, preparações para lavagem, preparações lubrificantes, ceras artificiais, ceras preparadas, produtos de conservação e limpeza, velas e artigos semelhantes, massas ou pastas para modelar, "ceras para dentistas" e composições para dentistas à base de gesso.'),
(35, 'Matérias albuminóides; produtos à base de amidos ou de féculas modificados; colas; enzimas.'),
(36, 'Pólvoras e explosivos; artigos de pirotecnia; fósforos; ligas pirofóricas; matérias inflamáveis.'),
(37, 'Produtos para fotografia e cinematografia.'),
(38, 'Produtos diversos das indústrias químicas.'),
(39, 'Plásticos e suas obras.'),
(40, 'Borracha e suas obras.'),
(41, 'Peles, exceto a peleteria (peles com pêlo*), e couros.'),
(42, 'Obras de couro; artigos de correeiro ou de seleiro; artigos de viagem, bolsas e artefatos semelhantes; obras de tripa.'),
(43, 'Peleteria (peles com pelo*) e suas obras; peleteria (peles com pelo*) artificial.'),
(44, 'Madeira, carvão vegetal e obras de madeira.'),
(45, 'Cortiça e suas obras.'),
(46, 'Obras de espartaria ou de cestaria.'),
(47, 'Pastas de madeira ou de outras matérias fibrosas celulósicas; teste ou cartão de reciclar (desperdícios e aparas).'),
(48, 'teste e cartão; obras de pasta de celulose, de teste ou de cartão.'),
(49, 'Livros, jornais, gravuras e outros produtos das indústrias gráficas; textos manuscritos ou datilografados, planos e plantas.'),
(50, 'Seda.'),
(51, 'Lã e pelos finos ou grosseiros; fios e tecidos de crina.'),
(52, 'Algodão.'),
(53, 'Outras fibras têxteis vegetais; fios de teste e tecido de fios de teste.'),
(54, 'Filamentos sintéticos ou artificiais.'),
(55, 'Fibras sintéticas ou artificiais, descontínuas.'),
(56, 'Pastas ("ouates"), feltros e falsos tecidos; fios especiais; cordéis, cordas e cabos; artigos de cordoaria.'),
(57, 'Tapetes e outros revestimentos para pavimentos, de matérias têxteis.'),
(58, 'Tecidos especiais; tecidos tufados; rendas; tapeçarias; passamanarias; bordados.'),
(59, 'Tecidos impregnados, revestidos, recobertos ou estratificados; artigos para usos técnicos de matérias têxteis.'),
(60, 'Tecidos de malha.'),
(61, 'Vestuário e seus acessórios, de malha.'),
(62, 'Vestuário e seus acessórios, exceto de malha.'),
(63, 'Outros artefatos têxteis confeccionados; sortidos; artefatos de matérias têxteis, calçados, chapéus e artefatos de uso semelhante, usados; trapos.'),
(64, 'Calçados, polainas e artefatos semelhantes, e suas partes.'),
(65, 'Chapéus e artefatos de uso semelhante, e suas partes.'),
(66, 'Guarda-chuvas, sombrinhas, guarda-sóis, bengalas, bengalas-assentos, chicotes, e suas partes.'),
(67, 'Penas e penugem preparadas, e suas obras; flores artificiais; obras de cabelo.'),
(68, 'Obras de pedra, gesso, cimento, amianto, mica ou de matérias semelhantes.'),
(69, 'Produtos cerâmicos.'),
(70, 'Vidro e suas obras.'),
(71, 'Pérolas naturais ou cultivadas, pedras preciosas ou semipreciosas e semelhantes, metais preciosos, metais folheados ou chapeados de metais preciosos, e suas obras; bijuterias; moedas.'),
(72, 'Ferro fundido, ferro e aço.'),
(73, 'Obras de ferro fundido, ferro ou aço.'),
(74, 'Cobre e suas obras.'),
(75, 'Níquel e suas obras.'),
(76, 'Alumínio e suas obras.'),
(77, '(Reservado para uma eventual utilização futura no SH).'),
(78, 'Chumbo e suas obras.'),
(79, 'Zinco e suas obras.'),
(80, 'Estanho e suas obras.'),
(81, 'Outros metais comuns; ceramais ("cermets"); obras dessas matérias.'),
(82, 'Ferramentas, artefatos de cutelaria e talheres, e suas partes, de metais comuns.'),
(83, 'Obras diversas de metais comuns.'),
(84, 'Reatores nucleares, caldeiras, máquinas, aparelhos e instrumentos mecânicos, e suas partes.'),
(85, 'Máquinas, aparelhos e materiais elétricos, e suas partes; aparelhos de gravação ou de reprodução de som, aparelhos de gravação ou de reprodução de imagens e de som em televisão, e suas partes e acessórios.'),
(86, 'Veículos e material para vias férreas ou semelhantes, e suas partes; aparelhos mecânicos (incluídos os eletromecânicos) de sinalização para vias de comunicação Veículos automóveis, tratores, ciclos e outros veículos terrestres, suas partes e acessórios.'),
(88, 'Aeronaves e aparelhos espaciais, e suas partes.'),
(89, 'Embarcações e estruturas flutuantes.'),
(90, 'Instrumentos e aparelhos de óptica, fotografia ou cinematografia, medida, controle ou de precisão; instrumentos e aparelhos médico-cirúrgicos; suas partes e acessórios.'),
(91, 'Aparelhos de relojoaria e suas partes.'),
(92, 'Instrumentos musicais, suas partes e acessórios.'),
(93, 'Armas e munições; suas partes e acessórios.'),
(94, 'Móveis, mobiliário médico-cirúrgico; colchões; iluminação e construção pré-fabricadas.'),
(95, 'Brinquedos, jogos, artigos para divertimento ou para esporte; suas partes e acessórios.'),
(96, 'Obras diversas.'),
(97, 'Objetos de arte, de coleção e antiguidades.'),
(98, '(Reservado para usos especiais pelas Partes Contratantes).'),
(99, 'Operações especiais (utilizado exclusivamente pelo Brasil para classificar operações especiais na exportação).');

insert into teste.cfop (id, descricao) values
(1101, 'Compra p/ industrialização ou produção rural'),
(1102, 'Compra p/ comercialização'),
(1111, 'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial'),
(1113, 'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil'),
(1116, 'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro'),
(1117, 'Compra p/ comercialização originada de encomenda p/ recebimento futuro'),
(1118, 'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem.'),
(1120, 'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente'),
(1121, 'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente'),
(1122, 'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente'),
(1124, 'Industrialização efetuada por outra empresa'),
(1125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria'),
(1126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS'),
(1128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN'),
(1151, 'Transferência p/ industrialização ou produção rural'),
(1152, 'Transferência p/ comercialização'),
(1153, 'Transferência de energia elétrica p/ distribuição'),
(1154, 'Transferência p/ utilização na prestação de serviço'),
(1201, 'Devolução de venda de produção do estabelecimento '),
(1202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros'),
(1203, 'Devolução de venda de produção do estabelecimento, destinada à ZFM ou ALC'),
(1204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC'),
(1205, 'Anulação de valor relativo à prestação de serviço de comunicação'),
(1206, 'Anulação de valor relativo à prestação de serviço de transporte'),
(1207, 'Anulação de valor relativo à venda de energia elétrica'),
(1208, 'Devolução de produção do estabelecimento, remetida em transferência'),
(1209, 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência'),
(1212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(1251, 'Compra de energia elétrica p/ distribuição ou comercialização'),
(1252, 'Compra de energia elétrica por estabelecimento industrial'),
(1253, 'Compra de energia elétrica por estabelecimento comercial'),
(1254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte'),
(1255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'),
(1256, 'Compra de energia elétrica por estabelecimento de produtor rural'),
(1257, 'Compra de energia elétrica p/ consumo por demanda contratada'),
(1301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza'),
(1302, 'Aquisição de serviço de comunicação por estabelecimento industrial'),
(1303, 'Aquisição de serviço de comunicação por estabelecimento comercial'),
(1304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'),
(1305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica'),
(1306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural'),
(1351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza'),
(1352, 'Aquisição de serviço de transporte por estabelecimento industrial'),
(1353, 'Aquisição de serviço de transporte por estabelecimento comercial'),
(1354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'),
(1355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'),
(1356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural'),
(1360, 'Aquisição de serviço de transporte por contribuinte-substituto em relação ao serviço de transporte'),
(1401, 'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST'),
(1403, 'Compra p/ comercialização em operação com mercadoria sujeita a ST'),
(1406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST'),
(1407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST'),
(1408, 'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST'),
(1409, 'Transferência p/ comercialização em operação com mercadoria sujeita a ST'),
(1410, 'Devolução de venda de mercadoria, de produção do estabelecimento, sujeita a ST'),
(1411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST'),
(1414, 'Retorno de mercadoria de produção do estabelecimento, remetida p/ venda fora do estabelecimento, sujeita a ST'),
(1415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST'),
(1451, 'Retorno de animal do estabelecimento produtor'),
(1452, 'Retorno de insumo não utilizado na produção'),
(1501, 'Entrada de mercadoria recebida com fim específico de exportação'),
(1503, 'Entrada decorrente de devolução de produto, de fabricação do estabelecimento, remetido com fim específico de exportação'),
(1504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros'),
(1505, 'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.'),
(1506, 'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.'),
(1551, 'Compra de bem p/ o ativo imobilizado'),
(1552, 'Transferência de bem do ativo imobilizado'),
(1553, 'Devolução de venda de bem do ativo imobilizado'),
(1554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento'),
(1555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento'),
(1556, 'Compra de material p/ uso ou consumo'),
(1557, 'Transferência de material p/ uso ou consumo'),
(1601, 'Recebimento, por transferência, de crédito de ICMS'),
(1602, 'Recebimento, por transferência, de saldo credor do ICMS, de outro estabelecimento da mesma empresa, p/ compensação de saldo devedor do imposto. '),
(1603, 'Ressarcimento de ICMS retido por substituição tributária'),
(1604, 'Lançamento do crédito relativo à compra de bem p/ o ativo imobilizado'),
(1605, 'Recebimento, por transferência, de saldo devedor do ICMS de outro estabelecimento da mesma empresa'),
(1651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente'),
(1652, 'Compra de combustível ou lubrificante p/ comercialização'),
(1653, 'Compra de combustível ou lubrificante por consumidor ou usuário final'),
(1658, 'Transferência de combustível ou lubrificante p/ industrialização'),
(1659, 'Transferência de combustível ou lubrificante p/ comercialização'),
(1660, 'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente'),
(1661, 'Devolução de venda de combustível ou lubrificante destinados à comercialização'),
(1662, 'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final'),
(1663, 'Entrada de combustível ou lubrificante p/ armazenagem'),
(1664, 'Retorno de combustível ou lubrificante remetidos p/ armazenagem'),
(1901, 'Entrada p/ industrialização por encomenda'),
(1902, 'Retorno de mercadoria remetida p/ industrialização por encomenda'),
(1903, 'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo'),
(1904, 'Retorno de remessa p/ venda fora do estabelecimento'),
(1905, 'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral'),
(1906, 'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral'),
(1907, 'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral'),
(1908, 'Entrada de bem por conta de contrato de comodato'),
(1909, 'Retorno de bem remetido por conta de contrato de comodato'),
(1910, 'Entrada de bonificação, doação ou brinde'),
(1911, 'Entrada de amostra grátis'),
(1912, 'Entrada de mercadoria ou bem recebido p/ demonstração'),
(1913, 'Retorno de mercadoria ou bem remetido p/ demonstração'),
(1914, 'Retorno de mercadoria ou bem remetido p/ exposição ou feira'),
(1915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo'),
(1916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo'),
(1917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial'),
(1918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial'),
(1919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial'),
(1920, 'Entrada de vasilhame ou sacaria'),
(1921, 'Retorno de vasilhame ou sacaria'),
(1922, 'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro'),
(1923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'),
(1924, 'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(1925, 'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(1926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação'),
(1931, 'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço.'),
(1932, 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador'),
(1933, 'Aquisição de serviço tributado pelo Imposto sobre Serviços de Qualquer Natureza'),
(1934, 'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral'),
(1949, 'Outra entrada de mercadoria ou prestação de serviço não especificada'),
(2101, 'Compra p/ industrialização ou produção rural'),
(2102, 'Compra p/ comercialização'),
(2111, 'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial'),
(2113, 'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil'),
(2116, 'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro'),
(2117, 'Compra p/ comercialização originada de encomenda p/ recebimento futuro'),
(2118, 'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem'),
(2120, 'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente'),
(2121, 'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente'),
(2122, 'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente'),
(2124, 'Industrialização efetuada por outra empresa'),
(2125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria'),
(2126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS'),
(2128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN'),
(2151, 'Transferência p/ industrialização ou produção rural'),
(2152, 'Transferência p/ comercialização'),
(2153, 'Transferência de energia elétrica p/ distribuição'),
(2154, 'Transferência p/ utilização na prestação de serviço'),
(2201, 'Devolução de venda de produção do estabelecimento'),
(2202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros'),
(2203, 'Devolução de venda de produção do estabelecimento destinada à ZFM ou ALC'),
(2204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC'),
(2205, 'Anulação de valor relativo à prestação de serviço de comunicação'),
(2206, 'Anulação de valor relativo à prestação de serviço de transporte'),
(2207, 'Anulação de valor relativo à venda de energia elétrica'),
(2208, 'Devolução de produção do estabelecimento, remetida em transferência.'),
(2209, 'Devolução de mercadoria adquirida ou recebida de terceiros e remetida em transferência'),
(2212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(2251, 'Compra de energia elétrica p/ distribuição ou comercialização'),
(2252, 'Compra de energia elétrica por estabelecimento industrial'),
(2253, 'Compra de energia elétrica por estabelecimento comercial'),
(2254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte'),
(2255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'),
(2256, 'Compra de energia elétrica por estabelecimento de produtor rural'),
(2257, 'Compra de energia elétrica p/ consumo por demanda contratada'),
(2301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza'),
(2302, 'Aquisição de serviço de comunicação por estabelecimento industrial'),
(2303, 'Aquisição de serviço de comunicação por estabelecimento comercial'),
(2304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'),
(2305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica'),
(2306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural'),
(2351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza'),
(2352, 'Aquisição de serviço de transporte por estabelecimento industrial'),
(2353, 'Aquisição de serviço de transporte por estabelecimento comercial'),
(2354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'),
(2355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'),
(2356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural'),
(2401, 'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST'),
(2403, 'Compra p/ comercialização em operação com mercadoria sujeita a ST'),
(2406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST'),
(2407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST'),
(2408, 'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST'),
(2409, 'Transferência p/ comercialização em operação com mercadoria sujeita a ST'),
(2410, 'Devolução de venda de produção do estabelecimento, quando o produto sujeito a ST'),
(2411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST'),
(2414, 'Retorno de produção do estabelecimento, remetida p/ venda fora do estabelecimento, quando o produto sujeito a ST'),
(2415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST'),
(2501, 'Entrada de mercadoria recebida com fim específico de exportação'),
(2503, 'Entrada decorrente de devolução de produto industrializado pelo estabelecimento, remetido com fim específico de exportação'),
(2504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros'),
(2505, 'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.'),
(2506, 'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.'),
(2551, 'Compra de bem p/ o ativo imobilizado'),
(2552, 'Transferência de bem do ativo imobilizado'),
(2553, 'Devolução de venda de bem do ativo imobilizado'),
(2554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento'),
(2555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento'),
(2556, 'Compra de material p/ uso ou consumo'),
(2557, 'Transferência de material p/ uso ou consumo'),
(2603, 'Ressarcimento de ICMS retido por substituição tributária'),
(2651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente'),
(2652, 'Compra de combustível ou lubrificante p/ comercialização'),
(2653, 'Compra de combustível ou lubrificante por consumidor ou usuário final'),
(2658, 'Transferência de combustível ou lubrificante p/ industrialização'),
(2659, 'Transferência de combustível ou lubrificante p/ comercialização '),
(2660, 'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente'),
(2661, 'Devolução de venda de combustível ou lubrificante destinados à comercialização'),
(2662, 'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final'),
(2663, 'Entrada de combustível ou lubrificante p/ armazenagem'),
(2664, 'Retorno de combustível ou lubrificante remetidos p/ armazenagem'),
(2901, 'Entrada p/ industrialização por encomenda'),
(2902, 'Retorno de mercadoria remetida p/ industrialização por encomenda'),
(2903, 'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo'),
(2904, 'Retorno de remessa p/ venda fora do estabelecimento'),
(2905, 'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral'),
(2906, 'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral'),
(2907, 'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral'),
(2908, 'Entrada de bem por conta de contrato de comodato'),
(2909, 'Retorno de bem remetido por conta de contrato de comodato'),
(2910, 'Entrada de bonificação, doação ou brinde'),
(2911, 'Entrada de amostra grátis'),
(2912, 'Entrada de mercadoria ou bem recebido p/ demonstração'),
(2913, 'Retorno de mercadoria ou bem remetido p/ demonstração'),
(2914, 'Retorno de mercadoria ou bem remetido p/ exposição ou feira'),
(2915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo'),
(2916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo'),
(2917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial'),
(2918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial'),
(2919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial'),
(2920, 'Entrada de vasilhame ou sacaria'),
(2921, 'Retorno de vasilhame ou sacaria'),
(2922, 'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro'),
(2923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'),
(2924, 'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(2925, 'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(2931, 'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço  '),
(2932, 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador '),
(2933, 'Aquisição de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza'),
(2934, 'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral'),
(2949, 'Outra entrada de mercadoria ou prestação de serviço não especificado'),
(3101, 'Compra p/ industrialização ou produção rural'),
(3102, 'Compra p/ comercialização'),
(3126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS'),
(3127, 'Compra p/ industrialização sob o regime de drawback '),
(3128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN'),
(3129, 'Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(3201, 'Devolução de venda de produção do estabelecimento'),
(3202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros'),
(3205, 'Anulação de valor relativo à prestação de serviço de comunicação'),
(3206, 'Anulação de valor relativo à prestação de serviço de transporte'),
(3207, 'Anulação de valor relativo à venda de energia elétrica'),
(3211, 'Devolução de venda de produção do estabelecimento sob o regime de drawback '),
(3212, 'Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(3251, 'Compra de energia elétrica p/ distribuição ou comercialização'),
(3301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza'),
(3351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza'),
(3352, 'Aquisição de serviço de transporte por estabelecimento industrial'),
(3353, 'Aquisição de serviço de transporte por estabelecimento comercial'),
(3354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'),
(3355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'),
(3356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural'),
(3503, 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação'),
(3551, 'Compra de bem p/ o ativo imobilizado'),
(3553, 'Devolução de venda de bem do ativo imobilizado'),
(3556, 'Compra de material p/ uso ou consumo'),
(3651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente'),
(3652, 'Compra de combustível ou lubrificante p/ comercialização'),
(3653, 'Compra de combustível ou lubrificante por consumidor ou usuário final'),
(3930, 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária'),
(3949, 'Outra entrada de mercadoria ou prestação de serviço não especificado'),
(5101, 'Venda de produção do estabelecimento'),
(5102, 'Venda de mercadoria adquirida ou recebida de terceiros'),
(5103, 'Venda de produção do estabelecimento efetuada fora do estabelecimento'),
(5104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'),
(5105, 'Venda de produção do estabelecimento que não deva por ele transitar'),
(5106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar '),
(5109, 'Venda de produção do estabelecimento destinada à ZFM ou ALC'),
(5110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC'),
(5111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial'),
(5112, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial'),
(5113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'),
(5114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil'),
(5115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil'),
(5116, 'Venda de produção do estabelecimento originada de encomenda p/ entrega futura'),
(5117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura'),
(5118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'),
(5119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'),
(5120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem'),
(5122, 'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'),
(5123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'),
(5124, 'Industrialização efetuada p/ outra empresa'),
(5125, 'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria'),
(5129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(5152, 'Transferência de mercadoria adquirida ou recebida de terceiros'),
(5153, 'Transferência de energia elétrica'),
(5155, 'Transferência de produção do estabelecimento, que não deva por ele transitar'),
(5156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'),
(5201, 'Devolução de compra p/ industrialização ou produção rural'),
(5202, 'Devolução de compra p/ comercialização'),
(5205, 'Anulação de valor relativo a aquisição de serviço de comunicação'),
(5206, 'Anulação de valor relativo a aquisição de serviço de transporte'),
(5207, 'Anulação de valor relativo à compra de energia elétrica'),
(5208, 'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural '),
(5209, 'Devolução de mercadoria recebida em transferência p/ comercialização'),
(5210, 'Devolução de compra p/ utilização na prestação de serviço'),
(5251, 'Venda de energia elétrica p/ distribuição ou comercialização'),
(5252, 'Venda de energia elétrica p/ estabelecimento industrial'),
(5253, 'Venda de energia elétrica p/ estabelecimento comercial'),
(5254, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte'),
(5255, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação'),
(5256, 'Venda de energia elétrica p/ estabelecimento de produtor rural'),
(5257, 'Venda de energia elétrica p/ consumo por demanda contratada'),
(5258, 'Venda de energia elétrica a não contribuinte'),
(5301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza'),
(5302, 'Prestação de serviço de comunicação a estabelecimento industrial'),
(5303, 'Prestação de serviço de comunicação a estabelecimento comercial'),
(5304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'),
(5305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica'),
(5306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural'),
(5307, 'Prestação de serviço de comunicação a não contribuinte'),
(5351, 'Prestação de serviço de transporte p/ execução de serviço da mesma natureza'),
(5352, 'Prestação de serviço de transporte a estabelecimento industrial'),
(5353, 'Prestação de serviço de transporte a estabelecimento comercial'),
(5354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'),
(5355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica'),
(5356, 'Prestação de serviço de transporte a estabelecimento de produtor rural'),
(5357, 'Prestação de serviço de transporte a não contribuinte'),
(5359, 'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  '),
(5360, 'Prestação de serviço de transporte a contribuinte-substituto em relação ao serviço de transporte'),
(5401, 'Venda de produção do estabelecimento quando o produto esteja sujeito a ST'),
(5402, 'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto'),
(5403, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituto'),
(5405, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituído'),
(5408, 'Transferência de produção do estabelecimento quando o produto sujeito a ST'),
(5409, 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST'),
(5410, 'Devolução de compra p/ industrialização de mercadoria sujeita a ST'),
(5411, 'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST'),
(5412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST'),
(5413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST.'),
(5414, 'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST'),
(5415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, em operação com mercadoria sujeita a ST'),
(5451, 'Remessa de animal e de insumo p/ estabelecimento produtor'),
(5501, 'Remessa de produção do estabelecimento, com fim específico de exportação'),
(5502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'),
(5503, 'Devolução de mercadoria recebida com fim específico de exportação'),
(5504, 'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.'),
(5505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.'),
(5551, 'Venda de bem do ativo imobilizado'),
(5552, 'Transferência de bem do ativo imobilizado'),
(5553, 'Devolução de compra de bem p/ o ativo imobilizado'),
(5554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento'),
(5555, 'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento'),
(5556, 'Devolução de compra de material de uso ou consumo'),
(5557, 'Transferência de material de uso ou consumo'),
(5601, 'Transferência de crédito de ICMS acumulado'),
(5602, 'Transferência de saldo credor do ICMS, p/ outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor do ICMS'),
(5603, 'Ressarcimento de ICMS retido por substituição tributária'),
(5605, 'Transferência de saldo devedor do ICMS de outro estabelecimento da mesma empresa  '),
(5606, 'Utilização de saldo credor do ICMS p/ extinção por compensação de débitos fiscais'),
(5651, 'Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente'),
(5652, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização'),
(5653, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final'),
(5654, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente'),
(5655, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização'),
(5656, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final'),
(5657, 'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento'),
(5658, 'Transferência de combustível ou lubrificante de produção do estabelecimento'),
(5659, 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros'),
(5660, 'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente'),
(5661, 'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização'),
(5662, 'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final'),
(5663, 'Remessa p/ armazenagem de combustível ou lubrificante'),
(5664, 'Retorno de combustível ou lubrificante recebidos p/ armazenagem'),
(5665, 'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem'),
(5666, 'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem'),
(5667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF'),
(5901, 'Remessa p/ industrialização por encomenda'),
(5902, 'Retorno de mercadoria utilizada na industrialização por encomenda'),
(5903, 'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo'),
(5904, 'Remessa p/ venda fora do estabelecimento'),
(5905, 'Remessa p/ depósito fechado ou armazém geral'),
(5906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral'),
(5907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'),
(5908, 'Remessa de bem por conta de contrato de comodato'),
(5909, 'Retorno de bem recebido por conta de contrato de comodato'),
(5910, 'Remessa em bonificação, doação ou brinde'),
(5911, 'Remessa de amostra grátis'),
(5912, 'Remessa de mercadoria ou bem p/ demonstração'),
(5913, 'Retorno de mercadoria ou bem recebido p/ demonstração'),
(5914, 'Remessa de mercadoria ou bem p/ exposição ou feira'),
(5915, 'Remessa de mercadoria ou bem p/ conserto ou reparo'),
(5916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo'),
(5917, 'Remessa de mercadoria em consignação mercantil ou industrial'),
(5918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial'),
(5919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial'),
(5920, 'Remessa de vasilhame ou sacaria'),
(5921, 'Devolução de vasilhame ou sacaria'),
(5922, 'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura'),
(5923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado.'),
(5924, 'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(5925, 'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente'),
(5926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação'),
(5927, 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração'),
(5928, 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa'),
(5929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF'),
(5931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço'),
(5932, 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador'),
(5933, 'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza'),
(5934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado.'),
(5949, 'Outra saída de mercadoria ou prestação de serviço não especificado'),
(6101, 'Venda de produção do estabelecimento'),
(6102, 'Venda de mercadoria adquirida ou recebida de terceiros'),
(6103, 'Venda de produção do estabelecimento, efetuada fora do estabelecimento'),
(6104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'),
(6105, 'Venda de produção do estabelecimento que não deva por ele transitar'),
(6106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'),
(6107, 'Venda de produção do estabelecimento, destinada a não contribuinte'),
(6108, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte'),
(6109, 'Venda de produção do estabelecimento destinada à ZFM ou ALC'),
(6110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC'),
(6111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial'),
(6112, 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial'),
(6113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'),
(6114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil'),
(6115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil'),
(6116, 'Venda de produção do estabelecimento originada de encomenda p/ entrega futura'),
(6117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura'),
(6118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'),
(6119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'),
(6120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem'),
(6122, 'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'),
(6123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'),
(6124, 'Industrialização efetuada p/ outra empresa'),
(6125, 'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria'),
(6129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(6151, 'Transferência de produção do estabelecimento'),
(6152, 'Transferência de mercadoria adquirida ou recebida de terceiros'),
(6153, 'Transferência de energia elétrica'),
(6155, 'Transferência de produção do estabelecimento, que não deva por ele transitar'),
(6156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'),
(6201, 'Devolução de compra p/ industrialização ou produção rural'),
(6202, 'Devolução de compra p/ comercialização'),
(6205, 'Anulação de valor relativo a aquisição de serviço de comunicação'),
(6206, 'Anulação de valor relativo a aquisição de serviço de transporte'),
(6207, 'Anulação de valor relativo à compra de energia elétrica'),
(6208, 'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural '),
(6209, 'Devolução de mercadoria recebida em transferência p/ comercialização'),
(6210, 'Devolução de compra p/ utilização na prestação de serviço'),
(6251, 'Venda de energia elétrica p/ distribuição ou comercialização'),
(6252, 'Venda de energia elétrica p/ estabelecimento industrial'),
(6253, 'Venda de energia elétrica p/ estabelecimento comercial'),
(6254, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte'),
(6255, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação'),
(6256, 'Venda de energia elétrica p/ estabelecimento de produtor rural'),
(6257, 'Venda de energia elétrica p/ consumo por demanda contratada'),
(6258, 'Venda de energia elétrica a não contribuinte'),
(6301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza'),
(6302, 'Prestação de serviço de comunicação a estabelecimento industrial'),
(6303, 'Prestação de serviço de comunicação a estabelecimento comercial'),
(6304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'),
(6305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica'),
(6306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural'),
(6307, 'Prestação de serviço de comunicação a não contribuinte'),
(6351, 'Prestação de serviço de transporte p/ execução de serviço da mesma natureza'),
(6352, 'Prestação de serviço de transporte a estabelecimento industrial'),
(6353, 'Prestação de serviço de transporte a estabelecimento comercial'),
(6354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'),
(6355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica'),
(6356, 'Prestação de serviço de transporte a estabelecimento de produtor rural'),
(6357, 'Prestação de serviço de transporte a não contribuinte'),
(6359, 'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  '),
(6360, 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte  '),
(6401, 'Venda de produção do estabelecimento quando o produto sujeito a ST'),
(6402, 'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto'),
(6403, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST, na condição de contribuinte substituto'),
(6404, 'Venda de mercadoria sujeita a ST, cujo imposto já tenha sido retido anteriormente'),
(6408, 'Transferência de produção do estabelecimento quando o produto sujeito a ST'),
(6409, 'Transferência de mercadoria adquirida ou recebida de terceiros, sujeita a ST'),
(6410, 'Devolução de compra p/ industrialização ou ptrodução rural quando a mercadoria sujeita a ST'),
(6411, 'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST'),
(6412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST'),
(6413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST'),
(6414, 'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST'),
(6415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, quando a referida ração com mercadoria sujeita a ST'),
(6501, 'Remessa de produção do estabelecimento, com fim específico de exportação'),
(6502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'),
(6503, 'Devolução de mercadoria recebida com fim específico de exportação'),
(6504, 'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.'),
(6505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.'),
(6551, 'Venda de bem do ativo imobilizado'),
(6552, 'Transferência de bem do ativo imobilizado'),
(6553, 'Devolução de compra de bem p/ o ativo imobilizado'),
(6554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento'),
(6555, 'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento'),
(6556, 'Devolução de compra de material de uso ou consumo'),
(6557, 'Transferência de material de uso ou consumo'),
(6603, 'Ressarcimento de ICMS retido por substituição tributária'),
(6651, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à industrialização subseqüente'),
(6652, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização'),
(6653, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final '),
(6654, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente '),
(6655, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização'),
(6656, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final'),
(6657, 'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento'),
(6658, 'Transferência de combustível ou lubrificante de produção do estabelecimento'),
(6659, 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros'),
(6660, 'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente'),
(6661, 'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização'),
(6662, 'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final'),
(6663, 'Remessa p/ armazenagem de combustível ou lubrificante'),
(6664, 'Retorno de combustível ou lubrificante recebidos p/ armazenagem'),
(6665, 'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem'),
(6666, 'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem'),
(6667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF diferente da que ocorrer o consumo'),
(6901, 'Remessa p/ industrialização por encomenda'),
(6902, 'Retorno de mercadoria utilizada na industrialização por encomenda'),
(6903, 'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo'),
(6904, 'Remessa p/ venda fora do estabelecimento'),
(6905, 'Remessa p/ depósito fechado ou armazém geral'),
(6906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral'),
(6907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'),
(6908, 'Remessa de bem por conta de contrato de comodato'),
(6909, 'Retorno de bem recebido por conta de contrato de comodato'),
(6910, 'Remessa em bonificação, doação ou brinde'),
(6911, 'Remessa de amostra grátis'),
(6912, 'Remessa de mercadoria ou bem p/ demonstração'),
(6913, 'Retorno de mercadoria ou bem recebido p/ demonstração'),
(6914, 'Remessa de mercadoria ou bem p/ exposição ou feira'),
(6915, 'Remessa de mercadoria ou bem p/ conserto ou reparo'),
(6916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo'),
(6917, 'Remessa de mercadoria em consignação mercantil ou industrial'),
(6918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial'),
(6919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial'),
(6920, 'Remessa de vasilhame ou sacaria'),
(6921, 'Devolução de vasilhame ou sacaria'),
(6922, 'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura'),
(6923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado'),
(6924, 'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'),
(6925, 'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente'),
(6929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF'),
(6931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço'),
(6932, 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador'),
(6933, 'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza '),
(6934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado'),
(6949, 'Outra saída de mercadoria ou prestação de serviço não especificado'),
(7101, 'Venda de produção do estabelecimento'),
(7102, 'Venda de mercadoria adquirida ou recebida de terceiros'),
(7105, 'Venda de produção do estabelecimento, que não deva por ele transitar'),
(7106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'),
(7127, 'Venda de produção do estabelecimento sob o regime de drawback '),
(7129, 'Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(7201, 'Devolução de compra p/ industrialização ou produção rural'),
(7202, 'Devolução de compra p/ comercialização'),
(7205, 'Anulação de valor relativo à aquisição de serviço de comunicação'),
(7206, 'Anulação de valor relativo a aquisição de serviço de transporte'),
(7207, 'Anulação de valor relativo à compra de energia elétrica'),
(7210, 'Devolução de compra p/ utilização na prestação de serviço'),
(7211, 'Devolução de compras p/ industrialização sob o regime de drawback '),
(7212, 'Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)'),
(7251, 'Venda de energia elétrica p/ o exterior'),
(7301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza'),
(7358, 'Prestação de serviço de transporte'),
(7501, 'Exportação de mercadorias recebidas com fim específico de exportação'),
(7551, 'Venda de bem do ativo imobilizado'),
(7553, 'Devolução de compra de bem p/ o ativo imobilizado'),
(7556, 'Devolução de compra de material de uso ou consumo'),
(7651, 'Venda de combustível ou lubrificante de produção do estabelecimento'),
(7654, 'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros'),
(7667, 'Venda de combustível ou lubrificante a consumidor ou usuário final'),
(7930, 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária'),
(7949, 'Outra saída de mercadoria ou prestação de serviço não especificado');


insert into teste.banco (codigo, descricao)
values
('000', 'Banco Bankpar S.A.'),
('001', 'Banco do Brasil S.A.'),
('003', 'Banco da Amazônia S.A.'),
('004', 'Banco do Nordeste do Brasil.A.'),
('012', 'Banco Standard de Investimentos S.'),
('014', 'Natixis Brasil S.A. Banco Múltiplo'),
('019', 'Banco Azteca do Brasil S.A.'),
('021', 'BANESTES S.A. Banco do Estado dospírito Santo'),
('024', 'Banco de Pernambuco S.A. - BANDEPE'),
('025', 'Banco Alfa S.A.'),
('029', 'Banco Banerj S.A.'),
('031', 'Banco Beg S.A.'),
('033', 'Banco Santander (Bril) S.A.'),
('036', 'Banco Bradesco BBI S.A.'),
('037', 'Banco do Estado do Pará S.'),
('039', 'Banco do Estado do Piauí S.A. -EP'),
('040', 'Banco Cargill S.A.'),
('041', 'Banco do Estado do Rio ande do Sul S.A.'),
('044', 'Banco BVA S.A.'),
('045', 'Banco Opportunity S.'),
('047', 'Banco do Estado de SergipS.A.'),
('062', 'Hipercard Banco Múltiplo S.A.'),
('063', 'Banco Ibi S.A. Banco Múltiplo'),
('064', 'Goldman Sachs do Brasil Banco Múltlo S.A.'),
('065', 'Banco Bracce S.A.'),
('066', 'Banco Morgan Stanley S.'),
('069', 'BPN Brasil Banco Múltiplo S.'),
('070', 'BRB - Banco de Brasília S.A.'),
('072', 'Banco Rural Mais S.A.'),
('073', 'BB Banco Popular do Brasil.A.'),
('074', 'Banco J. Safra S.A.'),
('075', 'Banco CR2 S.A.'),
('076', 'Banco KDB S.A.'),
('078', 'BES Investimento dorasil S.A.-Banco de Investimento'),
('079', 'JBS Banco S.A.'),
('084', 'Unicred Norte do Paná'),
('096', 'Banco BM&F de Serviços de quidação e Custódia S.A'),
('104', 'Caixa Econômica Federal'),
('107', 'Banco BBM S.A.'),
('168', 'HSBC Finance (Brasi S.A. - Banco Múltiplo'),
('184', 'Banco Itaú BBA S.A.'),
('204', 'Banco Bradesco Cartões S.'),
('208', 'Banco BTG Pactual S.A.'),
('212', 'Banco Matone S.A.'),
('213', 'Banco Arbi S.A.'),
('214', 'Banco Dibens S.A.'),
('215', 'Banco Comercial e de Iestimento Sudameris S.A.'),
('217', 'Banco John Deere S.A.'),
('218', 'Banco Bonsucesso S.A.'),
('222', 'Banco Credit Agricole Bras S.A.'),
('224', 'Banco Fibra S.A.'),
('225', 'Banco Brascan S.A.'),
('229', 'Banco Cruzeiro do Sul S.'),
('230', 'Unicard Banco Múltiplo S.A'),
('233', 'Banco GE Capital S.A.'),
('237', 'Banco Bradesco S.A.'),
('241', 'Banco Clássico S.A.'),
('243', 'Banco Máxima S.A.'),
('246', 'Banco ABC Brasil S.'),
('248', 'Banco Boavista Interatlâico S.A.'),
('249', 'Banco Investcred Unibanco S.A.'),
('250', 'Banco Schahin S.A.'),
('254', 'Paraná Banco S.A.'),
('263', 'Banco Cacique S.A.'),
('265', 'Banco Fator S.A.'),
('266', 'Banco Cédula S.A.'),
('300', 'Banco de La Nacion Argtina'),
('318', 'Banco BMG S.A.'),
('320', 'Banco Industrial e mercial S.A.'),
('341', 'Itaú Unibanco S.A.'),
('356', 'Banco Real S.A.'),
('366', 'Banco Société Généra Brasil S.A.'),
('370', 'Banco WestLB do Brasil S.A.'),
('376', 'Banco J. P. Morgan S.A.'),
('389', 'Banco Mercantil do Brasil S.'),
('394', 'Banco Bradesco Financiamentos S.'),
('399', 'HSBC Bank Brasil S.A. - Banco Múltip'),
('409', 'UNIBANCO - União de Bancos Brasileiros S.'),
('412', 'Banco Capital S.A.'),
('422', 'Banco Safra S.A.'),
('453', 'Banco Rural S.A.'),
('456', 'Banco de Tokyo-Mitsubhi UFJ Brasil S.A.'),
('464', 'Banco Sumitomo Mitsui Brasileiro S.A.'),
('473', 'Banco Caixa Geral - Brasil S.A.'),
('477', 'Citibank N.A.'),
('479', 'Banco ItaúBank S'),
('487', 'Deutsche Bank S.A. - nco Alemão'),
('488', 'JPMorgan Chase Bank'),
('492', 'ING Bank N.V.'),
('494', 'Banco de La Republa Oriental del Uruguay'),
('495', 'Banco de La Provincia de Buenos Aires'),
('505', 'Banco Credit Suisse (Brasil) S.A.'),
('600', 'Banco Luso Brasileiro S.A.'),
('604', 'Banco Industrial do Brasil S.'),
('610', 'Banco VR S.A.'),
('611', 'Banco Paulista S.'),
('612', 'Banco Guanabara S.A'),
('613', 'Banco Pecúnia S.A.'),
('623', 'Banco Panamericano S.'),
('626', 'Banco Ficsa S.A.'),
('630', 'Banco Intercap S.A'),
('633', 'Banco Rendimento S.A'),
('634', 'Banco Triângulo S.A.'),
('637', 'Banco Sofisa S.A.'),
('638', 'Banco Prosper S.A.'),
('641', 'Banco Alvorada S.A.'),
('643', 'Banco Pine S.A.'),
('652', 'Itaú Unibanco HoldinS.A.'),
('653', 'Banco Indusval S.A.'),
('654', 'Banco A.J.Renner S.A.'),
('655', 'Banco Votorantim S.A.'),
('707', 'Banco Daycoval S.A.'),
('719', 'Banif-Banco Internacionado Funchal (Brasil)S.A.'),
('721', 'Banco Credibel S.A.'),
('724', 'Banco Porto Seguro S.'),
('734', 'Banco Gerdau S.A.'),
('735', 'Banco Pottencial S.'),
('738', 'Banco Morada S.A.'),
('739', 'Banco BGN S.A.'),
('740', 'Banco Barclays S.'),
('741', 'Banco Ribeirão Preto S.'),
('743', 'Banco Semear S.A.'),
('744', 'BankBoston N.A.'),
('745', 'Banco Citibank S.'),
('746', 'Banco Modal S.A.'),
('747', 'Banco Rabobank Internional Brasil S.A.'),
('748', 'Banco Cooperativo Sicredi S.A.'),
('749', 'Banco Simples S.A.'),
('751', 'Dresdner Bank Brasil S. - Banco Múltiplo'),
('752', 'Banco BNP Paribas Brasil S.A.'),
('753', 'NBC Bank Brasil S.A. - Banco Múltio'),
('755', 'Bank of America Merrill Lynch Banco Múltlo S.A.'),
('756', 'Banco Cooperativo do Brasil S.A. - BANCOOB'),
('757', 'Banco KEB do Brasil S.A.'),
('077_9', 'Banco Intermedium S.A.'),
('081_7', 'Concórdia Banco S.A.'),
('082_5', 'Banco Topázio S.A.'),
('083_3', 'Banco da China Brasil S.A.'),
('085_x', 'Cooperativa Central de Crédito Urbano-CECRED'),
('086_8', 'OBOE Crédito Financiamento e Investimento S.A.'),
('087_6', 'Cooperativa Unicred Central Santa Catarina'),
('088_4', 'Banco Randon S.A.'),
('089_2', 'Cooperativa de Crédito Rural da Região de Mogiana'),
('090_2', 'Cooperativa Central de Economia e Crédito Mutuo das Unicreds'),
('091_4', 'Unicred Central do Rio Grande do Sul'),
('092_2', 'Brickell S.A. Crédito, financiamento e Investimento'),
('094_2', 'Banco Petra S.A.'),
('097_3', 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.'),
('098_1', 'Credicorol Cooperativa de Crédito Rural'),
('099_x', 'Cooperativa Central de Economia e Credito Mutuo das Unicreds');	

-- senha 123
insert into teste.usuario (nome, datacadastro, senha, permiteemailproprio)
values('adm', current_timestamp, '202cb962ac59075b964b07152d234b70', false);

insert into teste.usuario_grupos values(1, 'CEO');

insert into teste.pessoa
(cnpj, datacadastro, defineusuario, definecliente, defineagente, definefornecedor, definevendedor, email, fantasia, fone, nome, representante, tipo, origem_id, usuario_id, ie, im, identidade, mae, nacionalidade, naturalidade, orgao, pai, incentivocultural, valorcredito, inativausuariotransferido, permitecompartilhacliente, permitecompartilhafornecedor, permitecompartilhamodulo, permitecompartilhaproduto)
values('74091177000187', current_timestamp, true, false, false, false, false, 'teste@hotmail.com', 'CLINICA MEDICA', '85 0000-0000', 'Clinica Ltda', 'Clinica Médica', 'PJ', 1, 1, '', '', '', '', '', '', '', '', false, 0, true, false, false, false, false);

insert into teste.parametro (codigo, grupo, valor, empresa_id) values('theme', 'MAIL', 'start', 1); 

insert into teste.formapgto 
(desconto, descricao, entrada, minimo, tipo, pessoa_id)
values(10, 'à vista', 100, 0, 'DIN', 1);

insert into teste.regrapgto 
(desconto, quantidade, tempo, formapgto_id, unifica, juro)
values(0, 1, 0, 1, FALSE, 0);

insert into teste.contingencia
(descricao, medida, empresa_id)
values
('aporte de capital dos sócios', 'NEGATIVO', 1),
('captação de recursos de terceiros', 'NEGATIVO', 1),
('negociação com fornecedor', 'NEGATIVO', 1),
('liberação de investimentos', 'NEGATIVO', 1),
('venda de ativos patrimoniais', 'NEGATIVO', 1),
('desconto de cheque/duplicata', 'NEGATIVO', 1),
('aplicação em investimentos', 'POSITIVO', 1),
('antecipação de passivo', 'POSITIVO', 1),
('aquisição de estoque', 'POSITIVO', 1),
('reserva de investimento', 'POSITIVO', 1);
